
target "SMRDydeploymentDemo" do
    platform:ios, '9.0'
    use_frameworks!
    
    pod 'PureLayout', :inhibit_warnings => true
    pod 'SDWebImage', :inhibit_warnings => true
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['ENABLE_BITCODE'] = 'NO' if config.build_settings['SDKROOT'] == 'iphoneos'
        end
    end
end
